[build]
  base = "Portfolio/portfolio-izeq" # Directory containing package.json
  publish = "Portfolio/portfolio-izeq/dist" # Directory containing built files
  command = "npm run build" # Build command
